/* File: raymondmodule.c
 * This file is auto-generated with f2py (version:1.23.5).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sun Apr 23 04:34:43 2023
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *raymond_error;
static PyObject *raymond_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKARRAY(check,tcheck,name) \
    if (!(check)) {\
        PyErr_SetString(raymond_error,"("tcheck") failed for "name);\
        /*goto capi_fail;*/\
    } else 
#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(raymond_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = raymond_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = raymond_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(raymond,RAYMOND)(double*,int*,int*,int*,double*);
extern void F_FUNC(impfila,IMPFILA)(double*,int*,int*,int*,double*,int*,int*);
extern void F_FUNC(filsub,FILSUB)(int*,int*,int*,double*,double*,double*,int*);
extern void F_FUNC_US(invlow_v,INVLOW_V)(int*,int*,double*,double*,double*,double*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*);
extern void F_FUNC(rhsini,RHSINI)(int*,int*,int*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** raymond **********************************/
static char doc_f2py_rout_raymond_raymond[] = "\
f = raymond(f,nlon,nlat,eps,[nlev,overwrite_f])\n\nWrapper for ``raymond``.\
\n\nParameters\n----------\n"
"f : input rank-2 array('d') with bounds (nlat * nlon,nlev)\n"
"nlon : input int\n"
"nlat : input int\n"
"eps : input float\n"
"\nOther Parameters\n----------------\n"
"overwrite_f : input int, optional\n    Default: 0\n"
"nlev : input int, optional\n    Default: shape(f, 1)\n"
"\nReturns\n-------\n"
"f : rank-2 array('d') with bounds (nlat * nlon,nlev)";
/* extern void F_FUNC(raymond,RAYMOND)(double*,int*,int*,int*,double*); */
static PyObject *f2py_rout_raymond_raymond(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *f = NULL;
    npy_intp f_Dims[2] = {-1, -1};
    const int f_Rank = 2;
    PyArrayObject *capi_f_tmp = NULL;
    int capi_f_intent = 0;
    int capi_overwrite_f = 0;
    PyObject *f_capi = Py_None;
    int nlon = 0;
    PyObject *nlon_capi = Py_None;
    int nlat = 0;
    PyObject *nlat_capi = Py_None;
    int nlev = 0;
    PyObject *nlev_capi = Py_None;
    double eps = 0;
    PyObject *eps_capi = Py_None;
    static char *capi_kwlist[] = {"f","nlon","nlat","eps","nlev","overwrite_f",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|Oi:raymond.raymond",\
        capi_kwlist,&f_capi,&nlon_capi,&nlat_capi,&eps_capi,&nlev_capi,&capi_overwrite_f))
        return NULL;
/*frompyobj*/
    /* Processing variable nlon */
        f2py_success = int_from_pyobj(&nlon,nlon_capi,"raymond.raymond() 2nd argument (nlon) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nlat */
        f2py_success = int_from_pyobj(&nlat,nlat_capi,"raymond.raymond() 3rd argument (nlat) can't be converted to int");
    if (f2py_success) {
    /* Processing variable eps */
        f2py_success = double_from_pyobj(&eps,eps_capi,"raymond.raymond() 4th argument (eps) can't be converted to double");
    if (f2py_success) {
    /* Processing variable f */
    capi_f_intent |= (capi_overwrite_f?0:F2PY_INTENT_COPY);
    f_Dims[0]=nlat * nlon;
    capi_f_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    capi_f_tmp = array_from_pyobj(NPY_DOUBLE,f_Dims,f_Rank,capi_f_intent,f_capi);
    if (capi_f_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 1st argument `f' of raymond.raymond to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        f = (double *)(PyArray_DATA(capi_f_tmp));

    CHECKARRAY(shape(f, 0) == nlat * nlon,"shape(f, 0) == nlat * nlon","1st argument f") {
    CHECKARRAY(shape(f, 0) == nlat * nlon,"shape(f, 0) == nlat * nlon","1st argument f") {
    /* Processing variable nlev */
    if (nlev_capi == Py_None) nlev = shape(f, 1); else
        f2py_success = int_from_pyobj(&nlev,nlev_capi,"raymond.raymond() 1st keyword (nlev) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(f, 1) == nlev,"shape(f, 1) == nlev","1st keyword nlev","raymond:nlev=%d",nlev) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(f,&nlon,&nlat,&nlev,&eps);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_f_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(f, 1) == nlev)*/
    } /*if (f2py_success) of nlev*/
    /* End of cleaning variable nlev */
    } /*CHECKARRAY(shape(f, 0) == nlat * nlon)*/
    } /*CHECKARRAY(shape(f, 0) == nlat * nlon)*/
    }  /*if (capi_f_tmp == NULL) ... else of f*/
    /* End of cleaning variable f */
    } /*if (f2py_success) of eps*/
    /* End of cleaning variable eps */
    } /*if (f2py_success) of nlat*/
    /* End of cleaning variable nlat */
    } /*if (f2py_success) of nlon*/
    /* End of cleaning variable nlon */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of raymond *******************************/

/********************************** impfila **********************************/
static char doc_f2py_rout_raymond_impfila[] = "\
f = impfila(f,nlon,nlat,eps,nx,nstep,[nlev,overwrite_f])\n\nWrapper for ``impfila``.\
\n\nParameters\n----------\n"
"f : input rank-2 array('d') with bounds (nlat * nlon,nlev)\n"
"nlon : input int\n"
"nlat : input int\n"
"eps : input float\n"
"nx : input int\n"
"nstep : input int\n"
"\nOther Parameters\n----------------\n"
"overwrite_f : input int, optional\n    Default: 0\n"
"nlev : input int, optional\n    Default: shape(f, 1)\n"
"\nReturns\n-------\n"
"f : rank-2 array('d') with bounds (nlat * nlon,nlev)";
/* extern void F_FUNC(impfila,IMPFILA)(double*,int*,int*,int*,double*,int*,int*); */
static PyObject *f2py_rout_raymond_impfila(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *f = NULL;
    npy_intp f_Dims[2] = {-1, -1};
    const int f_Rank = 2;
    PyArrayObject *capi_f_tmp = NULL;
    int capi_f_intent = 0;
    int capi_overwrite_f = 0;
    PyObject *f_capi = Py_None;
    int nlon = 0;
    PyObject *nlon_capi = Py_None;
    int nlat = 0;
    PyObject *nlat_capi = Py_None;
    int nlev = 0;
    PyObject *nlev_capi = Py_None;
    double eps = 0;
    PyObject *eps_capi = Py_None;
    int nx = 0;
    PyObject *nx_capi = Py_None;
    int nstep = 0;
    PyObject *nstep_capi = Py_None;
    static char *capi_kwlist[] = {"f","nlon","nlat","eps","nx","nstep","nlev","overwrite_f",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOO|Oi:raymond.impfila",\
        capi_kwlist,&f_capi,&nlon_capi,&nlat_capi,&eps_capi,&nx_capi,&nstep_capi,&nlev_capi,&capi_overwrite_f))
        return NULL;
/*frompyobj*/
    /* Processing variable nstep */
        f2py_success = int_from_pyobj(&nstep,nstep_capi,"raymond.impfila() 6th argument (nstep) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nlon */
        f2py_success = int_from_pyobj(&nlon,nlon_capi,"raymond.impfila() 2nd argument (nlon) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nlat */
        f2py_success = int_from_pyobj(&nlat,nlat_capi,"raymond.impfila() 3rd argument (nlat) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nx */
        f2py_success = int_from_pyobj(&nx,nx_capi,"raymond.impfila() 5th argument (nx) can't be converted to int");
    if (f2py_success) {
    /* Processing variable eps */
        f2py_success = double_from_pyobj(&eps,eps_capi,"raymond.impfila() 4th argument (eps) can't be converted to double");
    if (f2py_success) {
    /* Processing variable f */
    capi_f_intent |= (capi_overwrite_f?0:F2PY_INTENT_COPY);
    f_Dims[0]=nlat * nlon;
    capi_f_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    capi_f_tmp = array_from_pyobj(NPY_DOUBLE,f_Dims,f_Rank,capi_f_intent,f_capi);
    if (capi_f_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 1st argument `f' of raymond.impfila to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        f = (double *)(PyArray_DATA(capi_f_tmp));

    CHECKARRAY(shape(f, 0) == nlat * nlon,"shape(f, 0) == nlat * nlon","1st argument f") {
    CHECKARRAY(shape(f, 0) == nlat * nlon,"shape(f, 0) == nlat * nlon","1st argument f") {
    /* Processing variable nlev */
    if (nlev_capi == Py_None) nlev = shape(f, 1); else
        f2py_success = int_from_pyobj(&nlev,nlev_capi,"raymond.impfila() 1st keyword (nlev) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(f, 1) == nlev,"shape(f, 1) == nlev","1st keyword nlev","impfila:nlev=%d",nlev) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(f,&nlon,&nlat,&nlev,&eps,&nx,&nstep);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_f_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(f, 1) == nlev)*/
    } /*if (f2py_success) of nlev*/
    /* End of cleaning variable nlev */
    } /*CHECKARRAY(shape(f, 0) == nlat * nlon)*/
    } /*CHECKARRAY(shape(f, 0) == nlat * nlon)*/
    }  /*if (capi_f_tmp == NULL) ... else of f*/
    /* End of cleaning variable f */
    } /*if (f2py_success) of eps*/
    /* End of cleaning variable eps */
    } /*if (f2py_success) of nx*/
    /* End of cleaning variable nx */
    } /*if (f2py_success) of nlat*/
    /* End of cleaning variable nlat */
    } /*if (f2py_success) of nlon*/
    /* End of cleaning variable nlon */
    } /*if (f2py_success) of nstep*/
    /* End of cleaning variable nstep */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of impfila *******************************/

/*********************************** filsub ***********************************/
static char doc_f2py_rout_raymond_filsub[] = "\
xy = filsub(nstep,xy,eps,wrk,[nlon,nlat,nx,overwrite_xy])\n\nWrapper for ``filsub``.\
\n\nParameters\n----------\n"
"nstep : input int\n"
"xy : input rank-2 array('d') with bounds (nlon,nlat)\n"
"eps : input float\n"
"wrk : input rank-2 array('d') with bounds (nx,*)\n"
"\nOther Parameters\n----------------\n"
"nlon : input int, optional\n    Default: shape(xy, 0)\n"
"nlat : input int, optional\n    Default: shape(xy, 1)\n"
"overwrite_xy : input int, optional\n    Default: 0\n"
"nx : input int, optional\n    Default: shape(wrk, 0)\n"
"\nReturns\n-------\n"
"xy : rank-2 array('d') with bounds (nlon,nlat)";
/* extern void F_FUNC(filsub,FILSUB)(int*,int*,int*,double*,double*,double*,int*); */
static PyObject *f2py_rout_raymond_filsub(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,double*,double*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int nlon = 0;
    PyObject *nlon_capi = Py_None;
    int nlat = 0;
    PyObject *nlat_capi = Py_None;
    int nstep = 0;
    PyObject *nstep_capi = Py_None;
    double *xy = NULL;
    npy_intp xy_Dims[2] = {-1, -1};
    const int xy_Rank = 2;
    PyArrayObject *capi_xy_tmp = NULL;
    int capi_xy_intent = 0;
    int capi_overwrite_xy = 0;
    PyObject *xy_capi = Py_None;
    double eps = 0;
    PyObject *eps_capi = Py_None;
    double *wrk = NULL;
    npy_intp wrk_Dims[2] = {-1, -1};
    const int wrk_Rank = 2;
    PyArrayObject *capi_wrk_tmp = NULL;
    int capi_wrk_intent = 0;
    PyObject *wrk_capi = Py_None;
    int nx = 0;
    PyObject *nx_capi = Py_None;
    static char *capi_kwlist[] = {"nstep","xy","eps","wrk","nlon","nlat","nx","overwrite_xy",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|OOOi:raymond.filsub",\
        capi_kwlist,&nstep_capi,&xy_capi,&eps_capi,&wrk_capi,&nlon_capi,&nlat_capi,&nx_capi,&capi_overwrite_xy))
        return NULL;
/*frompyobj*/
    /* Processing variable eps */
        f2py_success = double_from_pyobj(&eps,eps_capi,"raymond.filsub() 3rd argument (eps) can't be converted to double");
    if (f2py_success) {
    /* Processing variable nstep */
        f2py_success = int_from_pyobj(&nstep,nstep_capi,"raymond.filsub() 1st argument (nstep) can't be converted to int");
    if (f2py_success) {
    /* Processing variable wrk */
    ;
    capi_wrk_intent |= F2PY_INTENT_IN;
    capi_wrk_tmp = array_from_pyobj(NPY_DOUBLE,wrk_Dims,wrk_Rank,capi_wrk_intent,wrk_capi);
    if (capi_wrk_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 4th argument `wrk' of raymond.filsub to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        wrk = (double *)(PyArray_DATA(capi_wrk_tmp));

    /* Processing variable xy */
    capi_xy_intent |= (capi_overwrite_xy?0:F2PY_INTENT_COPY);
    ;
    capi_xy_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    capi_xy_tmp = array_from_pyobj(NPY_DOUBLE,xy_Dims,xy_Rank,capi_xy_intent,xy_capi);
    if (capi_xy_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 2nd argument `xy' of raymond.filsub to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        xy = (double *)(PyArray_DATA(capi_xy_tmp));

    /* Processing variable nlon */
    if (nlon_capi == Py_None) nlon = shape(xy, 0); else
        f2py_success = int_from_pyobj(&nlon,nlon_capi,"raymond.filsub() 1st keyword (nlon) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(xy, 0) == nlon,"shape(xy, 0) == nlon","1st keyword nlon","filsub:nlon=%d",nlon) {
    /* Processing variable nlat */
    if (nlat_capi == Py_None) nlat = shape(xy, 1); else
        f2py_success = int_from_pyobj(&nlat,nlat_capi,"raymond.filsub() 2nd keyword (nlat) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(xy, 1) == nlat,"shape(xy, 1) == nlat","2nd keyword nlat","filsub:nlat=%d",nlat) {
    /* Processing variable nx */
    if (nx_capi == Py_None) nx = shape(wrk, 0); else
        f2py_success = int_from_pyobj(&nx,nx_capi,"raymond.filsub() 3rd keyword (nx) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(wrk, 0) == nx,"shape(wrk, 0) == nx","3rd keyword nx","filsub:nx=%d",nx) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&nlon,&nlat,&nstep,xy,&eps,wrk,&nx);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_xy_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(wrk, 0) == nx)*/
    } /*if (f2py_success) of nx*/
    /* End of cleaning variable nx */
    } /*CHECKSCALAR(shape(xy, 1) == nlat)*/
    } /*if (f2py_success) of nlat*/
    /* End of cleaning variable nlat */
    } /*CHECKSCALAR(shape(xy, 0) == nlon)*/
    } /*if (f2py_success) of nlon*/
    /* End of cleaning variable nlon */
    }  /*if (capi_xy_tmp == NULL) ... else of xy*/
    /* End of cleaning variable xy */
    if((PyObject *)capi_wrk_tmp!=wrk_capi) {
        Py_XDECREF(capi_wrk_tmp); }
    }  /*if (capi_wrk_tmp == NULL) ... else of wrk*/
    /* End of cleaning variable wrk */
    } /*if (f2py_success) of nstep*/
    /* End of cleaning variable nstep */
    } /*if (f2py_success) of eps*/
    /* End of cleaning variable eps */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of filsub *******************************/

/********************************** invlow_v **********************************/
static char doc_f2py_rout_raymond_invlow_v[] = "\
invlow_v(bb,xans,h,ep,init,a,b,c,d,e,delta,beta,w,gam,ap,f,z,pi,[np,n])\n\nWrapper for ``invlow_v``.\
\n\nParameters\n----------\n"
"bb : input rank-2 array('d') with bounds (np,n)\n"
"xans : input rank-2 array('d') with bounds (np,n)\n"
"h : input rank-2 array('d') with bounds (np,n)\n"
"ep : input float\n"
"init : input int\n"
"a : input rank-1 array('d') with bounds (n)\n"
"b : input rank-1 array('d') with bounds (n)\n"
"c : input rank-1 array('d') with bounds (n)\n"
"d : input rank-1 array('d') with bounds (n)\n"
"e : input rank-1 array('d') with bounds (n)\n"
"delta : input rank-1 array('d') with bounds (n)\n"
"beta : input rank-1 array('d') with bounds (n)\n"
"w : input rank-1 array('d') with bounds (n)\n"
"gam : input rank-1 array('d') with bounds (n)\n"
"ap : input rank-1 array('d') with bounds (n)\n"
"f : input rank-1 array('d') with bounds (n)\n"
"z : input rank-1 array('d') with bounds (n)\n"
"pi : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"np : input int, optional\n    Default: shape(bb, 0)\n"
"n : input int, optional\n    Default: shape(bb, 1)";
/* extern void F_FUNC_US(invlow_v,INVLOW_V)(int*,int*,double*,double*,double*,double*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_raymond_invlow_v(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,double*,double*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int np = 0;
    PyObject *np_capi = Py_None;
    int n = 0;
    PyObject *n_capi = Py_None;
    double *bb = NULL;
    npy_intp bb_Dims[2] = {-1, -1};
    const int bb_Rank = 2;
    PyArrayObject *capi_bb_tmp = NULL;
    int capi_bb_intent = 0;
    PyObject *bb_capi = Py_None;
    double *xans = NULL;
    npy_intp xans_Dims[2] = {-1, -1};
    const int xans_Rank = 2;
    PyArrayObject *capi_xans_tmp = NULL;
    int capi_xans_intent = 0;
    PyObject *xans_capi = Py_None;
    double *h = NULL;
    npy_intp h_Dims[2] = {-1, -1};
    const int h_Rank = 2;
    PyArrayObject *capi_h_tmp = NULL;
    int capi_h_intent = 0;
    PyObject *h_capi = Py_None;
    double ep = 0;
    PyObject *ep_capi = Py_None;
    int init = 0;
    PyObject *init_capi = Py_None;
    double *a = NULL;
    npy_intp a_Dims[1] = {-1};
    const int a_Rank = 1;
    PyArrayObject *capi_a_tmp = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    double *b = NULL;
    npy_intp b_Dims[1] = {-1};
    const int b_Rank = 1;
    PyArrayObject *capi_b_tmp = NULL;
    int capi_b_intent = 0;
    PyObject *b_capi = Py_None;
    double *c = NULL;
    npy_intp c_Dims[1] = {-1};
    const int c_Rank = 1;
    PyArrayObject *capi_c_tmp = NULL;
    int capi_c_intent = 0;
    PyObject *c_capi = Py_None;
    double *d = NULL;
    npy_intp d_Dims[1] = {-1};
    const int d_Rank = 1;
    PyArrayObject *capi_d_tmp = NULL;
    int capi_d_intent = 0;
    PyObject *d_capi = Py_None;
    double *e = NULL;
    npy_intp e_Dims[1] = {-1};
    const int e_Rank = 1;
    PyArrayObject *capi_e_tmp = NULL;
    int capi_e_intent = 0;
    PyObject *e_capi = Py_None;
    double *delta = NULL;
    npy_intp delta_Dims[1] = {-1};
    const int delta_Rank = 1;
    PyArrayObject *capi_delta_tmp = NULL;
    int capi_delta_intent = 0;
    PyObject *delta_capi = Py_None;
    double *beta = NULL;
    npy_intp beta_Dims[1] = {-1};
    const int beta_Rank = 1;
    PyArrayObject *capi_beta_tmp = NULL;
    int capi_beta_intent = 0;
    PyObject *beta_capi = Py_None;
    double *w = NULL;
    npy_intp w_Dims[1] = {-1};
    const int w_Rank = 1;
    PyArrayObject *capi_w_tmp = NULL;
    int capi_w_intent = 0;
    PyObject *w_capi = Py_None;
    double *gam = NULL;
    npy_intp gam_Dims[1] = {-1};
    const int gam_Rank = 1;
    PyArrayObject *capi_gam_tmp = NULL;
    int capi_gam_intent = 0;
    PyObject *gam_capi = Py_None;
    double *ap = NULL;
    npy_intp ap_Dims[1] = {-1};
    const int ap_Rank = 1;
    PyArrayObject *capi_ap_tmp = NULL;
    int capi_ap_intent = 0;
    PyObject *ap_capi = Py_None;
    double *f = NULL;
    npy_intp f_Dims[1] = {-1};
    const int f_Rank = 1;
    PyArrayObject *capi_f_tmp = NULL;
    int capi_f_intent = 0;
    PyObject *f_capi = Py_None;
    double *z = NULL;
    npy_intp z_Dims[1] = {-1};
    const int z_Rank = 1;
    PyArrayObject *capi_z_tmp = NULL;
    int capi_z_intent = 0;
    PyObject *z_capi = Py_None;
    double *pi = NULL;
    npy_intp pi_Dims[1] = {-1};
    const int pi_Rank = 1;
    PyArrayObject *capi_pi_tmp = NULL;
    int capi_pi_intent = 0;
    PyObject *pi_capi = Py_None;
    static char *capi_kwlist[] = {"bb","xans","h","ep","init","a","b","c","d","e","delta","beta","w","gam","ap","f","z","pi","np","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOOOOO|OO:raymond.invlow_v",\
        capi_kwlist,&bb_capi,&xans_capi,&h_capi,&ep_capi,&init_capi,&a_capi,&b_capi,&c_capi,&d_capi,&e_capi,&delta_capi,&beta_capi,&w_capi,&gam_capi,&ap_capi,&f_capi,&z_capi,&pi_capi,&np_capi,&n_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable init */
        init = (int)PyObject_IsTrue(init_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable bb */
    ;
    capi_bb_intent |= F2PY_INTENT_IN;
    capi_bb_tmp = array_from_pyobj(NPY_DOUBLE,bb_Dims,bb_Rank,capi_bb_intent,bb_capi);
    if (capi_bb_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 1st argument `bb' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        bb = (double *)(PyArray_DATA(capi_bb_tmp));

    /* Processing variable ep */
        f2py_success = double_from_pyobj(&ep,ep_capi,"raymond.invlow_v() 4th argument (ep) can't be converted to double");
    if (f2py_success) {
    /* Processing variable n */
    if (n_capi == Py_None) n = shape(bb, 1); else
        f2py_success = int_from_pyobj(&n,n_capi,"raymond.invlow_v() 2nd keyword (n) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(bb, 1) == n,"shape(bb, 1) == n","2nd keyword n","invlow_v:n=%d",n) {
    /* Processing variable np */
    if (np_capi == Py_None) np = shape(bb, 0); else
        f2py_success = int_from_pyobj(&np,np_capi,"raymond.invlow_v() 1st keyword (np) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(bb, 0) == np,"shape(bb, 0) == np","1st keyword np","invlow_v:np=%d",np) {
    /* Processing variable a */
    a_Dims[0]=n;
    capi_a_intent |= F2PY_INTENT_IN;
    capi_a_tmp = array_from_pyobj(NPY_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
    if (capi_a_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 6th argument `a' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        a = (double *)(PyArray_DATA(capi_a_tmp));

    /* Processing variable b */
    b_Dims[0]=n;
    capi_b_intent |= F2PY_INTENT_IN;
    capi_b_tmp = array_from_pyobj(NPY_DOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
    if (capi_b_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 7th argument `b' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        b = (double *)(PyArray_DATA(capi_b_tmp));

    /* Processing variable c */
    c_Dims[0]=n;
    capi_c_intent |= F2PY_INTENT_IN;
    capi_c_tmp = array_from_pyobj(NPY_DOUBLE,c_Dims,c_Rank,capi_c_intent,c_capi);
    if (capi_c_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 8th argument `c' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        c = (double *)(PyArray_DATA(capi_c_tmp));

    /* Processing variable d */
    d_Dims[0]=n;
    capi_d_intent |= F2PY_INTENT_IN;
    capi_d_tmp = array_from_pyobj(NPY_DOUBLE,d_Dims,d_Rank,capi_d_intent,d_capi);
    if (capi_d_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 9th argument `d' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        d = (double *)(PyArray_DATA(capi_d_tmp));

    /* Processing variable e */
    e_Dims[0]=n;
    capi_e_intent |= F2PY_INTENT_IN;
    capi_e_tmp = array_from_pyobj(NPY_DOUBLE,e_Dims,e_Rank,capi_e_intent,e_capi);
    if (capi_e_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 10th argument `e' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        e = (double *)(PyArray_DATA(capi_e_tmp));

    /* Processing variable f */
    f_Dims[0]=n;
    capi_f_intent |= F2PY_INTENT_IN;
    capi_f_tmp = array_from_pyobj(NPY_DOUBLE,f_Dims,f_Rank,capi_f_intent,f_capi);
    if (capi_f_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 16th argument `f' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        f = (double *)(PyArray_DATA(capi_f_tmp));

    /* Processing variable z */
    z_Dims[0]=n;
    capi_z_intent |= F2PY_INTENT_IN;
    capi_z_tmp = array_from_pyobj(NPY_DOUBLE,z_Dims,z_Rank,capi_z_intent,z_capi);
    if (capi_z_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 17th argument `z' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        z = (double *)(PyArray_DATA(capi_z_tmp));

    /* Processing variable ap */
    ap_Dims[0]=n;
    capi_ap_intent |= F2PY_INTENT_IN;
    capi_ap_tmp = array_from_pyobj(NPY_DOUBLE,ap_Dims,ap_Rank,capi_ap_intent,ap_capi);
    if (capi_ap_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 15th argument `ap' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        ap = (double *)(PyArray_DATA(capi_ap_tmp));

    /* Processing variable h */
    h_Dims[0]=np,h_Dims[1]=n;
    capi_h_intent |= F2PY_INTENT_IN;
    capi_h_tmp = array_from_pyobj(NPY_DOUBLE,h_Dims,h_Rank,capi_h_intent,h_capi);
    if (capi_h_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 3rd argument `h' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        h = (double *)(PyArray_DATA(capi_h_tmp));

    /* Processing variable pi */
    pi_Dims[0]=n;
    capi_pi_intent |= F2PY_INTENT_IN;
    capi_pi_tmp = array_from_pyobj(NPY_DOUBLE,pi_Dims,pi_Rank,capi_pi_intent,pi_capi);
    if (capi_pi_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 18th argument `pi' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        pi = (double *)(PyArray_DATA(capi_pi_tmp));

    /* Processing variable gam */
    gam_Dims[0]=n;
    capi_gam_intent |= F2PY_INTENT_IN;
    capi_gam_tmp = array_from_pyobj(NPY_DOUBLE,gam_Dims,gam_Rank,capi_gam_intent,gam_capi);
    if (capi_gam_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 14th argument `gam' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        gam = (double *)(PyArray_DATA(capi_gam_tmp));

    /* Processing variable beta */
    beta_Dims[0]=n;
    capi_beta_intent |= F2PY_INTENT_IN;
    capi_beta_tmp = array_from_pyobj(NPY_DOUBLE,beta_Dims,beta_Rank,capi_beta_intent,beta_capi);
    if (capi_beta_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 12nd argument `beta' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        beta = (double *)(PyArray_DATA(capi_beta_tmp));

    /* Processing variable delta */
    delta_Dims[0]=n;
    capi_delta_intent |= F2PY_INTENT_IN;
    capi_delta_tmp = array_from_pyobj(NPY_DOUBLE,delta_Dims,delta_Rank,capi_delta_intent,delta_capi);
    if (capi_delta_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 11st argument `delta' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        delta = (double *)(PyArray_DATA(capi_delta_tmp));

    /* Processing variable w */
    w_Dims[0]=n;
    capi_w_intent |= F2PY_INTENT_IN;
    capi_w_tmp = array_from_pyobj(NPY_DOUBLE,w_Dims,w_Rank,capi_w_intent,w_capi);
    if (capi_w_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 13rd argument `w' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        w = (double *)(PyArray_DATA(capi_w_tmp));

    /* Processing variable xans */
    xans_Dims[0]=np,xans_Dims[1]=n;
    capi_xans_intent |= F2PY_INTENT_IN;
    capi_xans_tmp = array_from_pyobj(NPY_DOUBLE,xans_Dims,xans_Rank,capi_xans_intent,xans_capi);
    if (capi_xans_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 2nd argument `xans' of raymond.invlow_v to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        xans = (double *)(PyArray_DATA(capi_xans_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&np,&n,bb,xans,h,&ep,&init,a,b,c,d,e,delta,beta,w,gam,ap,f,z,pi);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_xans_tmp!=xans_capi) {
        Py_XDECREF(capi_xans_tmp); }
    }  /*if (capi_xans_tmp == NULL) ... else of xans*/
    /* End of cleaning variable xans */
    if((PyObject *)capi_w_tmp!=w_capi) {
        Py_XDECREF(capi_w_tmp); }
    }  /*if (capi_w_tmp == NULL) ... else of w*/
    /* End of cleaning variable w */
    if((PyObject *)capi_delta_tmp!=delta_capi) {
        Py_XDECREF(capi_delta_tmp); }
    }  /*if (capi_delta_tmp == NULL) ... else of delta*/
    /* End of cleaning variable delta */
    if((PyObject *)capi_beta_tmp!=beta_capi) {
        Py_XDECREF(capi_beta_tmp); }
    }  /*if (capi_beta_tmp == NULL) ... else of beta*/
    /* End of cleaning variable beta */
    if((PyObject *)capi_gam_tmp!=gam_capi) {
        Py_XDECREF(capi_gam_tmp); }
    }  /*if (capi_gam_tmp == NULL) ... else of gam*/
    /* End of cleaning variable gam */
    if((PyObject *)capi_pi_tmp!=pi_capi) {
        Py_XDECREF(capi_pi_tmp); }
    }  /*if (capi_pi_tmp == NULL) ... else of pi*/
    /* End of cleaning variable pi */
    if((PyObject *)capi_h_tmp!=h_capi) {
        Py_XDECREF(capi_h_tmp); }
    }  /*if (capi_h_tmp == NULL) ... else of h*/
    /* End of cleaning variable h */
    if((PyObject *)capi_ap_tmp!=ap_capi) {
        Py_XDECREF(capi_ap_tmp); }
    }  /*if (capi_ap_tmp == NULL) ... else of ap*/
    /* End of cleaning variable ap */
    if((PyObject *)capi_z_tmp!=z_capi) {
        Py_XDECREF(capi_z_tmp); }
    }  /*if (capi_z_tmp == NULL) ... else of z*/
    /* End of cleaning variable z */
    if((PyObject *)capi_f_tmp!=f_capi) {
        Py_XDECREF(capi_f_tmp); }
    }  /*if (capi_f_tmp == NULL) ... else of f*/
    /* End of cleaning variable f */
    if((PyObject *)capi_e_tmp!=e_capi) {
        Py_XDECREF(capi_e_tmp); }
    }  /*if (capi_e_tmp == NULL) ... else of e*/
    /* End of cleaning variable e */
    if((PyObject *)capi_d_tmp!=d_capi) {
        Py_XDECREF(capi_d_tmp); }
    }  /*if (capi_d_tmp == NULL) ... else of d*/
    /* End of cleaning variable d */
    if((PyObject *)capi_c_tmp!=c_capi) {
        Py_XDECREF(capi_c_tmp); }
    }  /*if (capi_c_tmp == NULL) ... else of c*/
    /* End of cleaning variable c */
    if((PyObject *)capi_b_tmp!=b_capi) {
        Py_XDECREF(capi_b_tmp); }
    }  /*if (capi_b_tmp == NULL) ... else of b*/
    /* End of cleaning variable b */
    if((PyObject *)capi_a_tmp!=a_capi) {
        Py_XDECREF(capi_a_tmp); }
    }  /*if (capi_a_tmp == NULL) ... else of a*/
    /* End of cleaning variable a */
    } /*CHECKSCALAR(shape(bb, 0) == np)*/
    } /*if (f2py_success) of np*/
    /* End of cleaning variable np */
    } /*CHECKSCALAR(shape(bb, 1) == n)*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    } /*if (f2py_success) of ep*/
    /* End of cleaning variable ep */
    if((PyObject *)capi_bb_tmp!=bb_capi) {
        Py_XDECREF(capi_bb_tmp); }
    }  /*if (capi_bb_tmp == NULL) ... else of bb*/
    /* End of cleaning variable bb */
    } /*if (f2py_success) of init*/
    /* End of cleaning variable init */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of invlow_v ******************************/

/*********************************** rhsini ***********************************/
static char doc_f2py_rout_raymond_rhsini[] = "\
rhs = rhsini(istep,xy,rhs,zeps,[nhor,n,overwrite_rhs])\n\nWrapper for ``rhsini``.\
\n\nParameters\n----------\n"
"istep : input int\n"
"xy : input rank-1 array('d') with bounds (*)\n"
"rhs : input rank-2 array('d') with bounds (nhor,n)\n"
"zeps : input float\n"
"\nOther Parameters\n----------------\n"
"nhor : input int, optional\n    Default: shape(rhs, 0)\n"
"n : input int, optional\n    Default: shape(rhs, 1)\n"
"overwrite_rhs : input int, optional\n    Default: 0\n"
"\nReturns\n-------\n"
"rhs : rank-2 array('d') with bounds (nhor,n)";
/* extern void F_FUNC(rhsini,RHSINI)(int*,int*,int*,double*,double*,double*); */
static PyObject *f2py_rout_raymond_rhsini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int nhor = 0;
    PyObject *nhor_capi = Py_None;
    int n = 0;
    PyObject *n_capi = Py_None;
    int istep = 0;
    PyObject *istep_capi = Py_None;
    double *xy = NULL;
    npy_intp xy_Dims[1] = {-1};
    const int xy_Rank = 1;
    PyArrayObject *capi_xy_tmp = NULL;
    int capi_xy_intent = 0;
    PyObject *xy_capi = Py_None;
    double *rhs = NULL;
    npy_intp rhs_Dims[2] = {-1, -1};
    const int rhs_Rank = 2;
    PyArrayObject *capi_rhs_tmp = NULL;
    int capi_rhs_intent = 0;
    int capi_overwrite_rhs = 0;
    PyObject *rhs_capi = Py_None;
    double zeps = 0;
    PyObject *zeps_capi = Py_None;
    static char *capi_kwlist[] = {"istep","xy","rhs","zeps","nhor","n","overwrite_rhs",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|OOi:raymond.rhsini",\
        capi_kwlist,&istep_capi,&xy_capi,&rhs_capi,&zeps_capi,&nhor_capi,&n_capi,&capi_overwrite_rhs))
        return NULL;
/*frompyobj*/
    /* Processing variable istep */
        f2py_success = int_from_pyobj(&istep,istep_capi,"raymond.rhsini() 1st argument (istep) can't be converted to int");
    if (f2py_success) {
    /* Processing variable rhs */
    capi_rhs_intent |= (capi_overwrite_rhs?0:F2PY_INTENT_COPY);
    ;
    capi_rhs_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    capi_rhs_tmp = array_from_pyobj(NPY_DOUBLE,rhs_Dims,rhs_Rank,capi_rhs_intent,rhs_capi);
    if (capi_rhs_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 3rd argument `rhs' of raymond.rhsini to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        rhs = (double *)(PyArray_DATA(capi_rhs_tmp));

    /* Processing variable xy */
    ;
    capi_xy_intent |= F2PY_INTENT_IN;
    capi_xy_tmp = array_from_pyobj(NPY_DOUBLE,xy_Dims,xy_Rank,capi_xy_intent,xy_capi);
    if (capi_xy_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : raymond_error,"failed in converting 2nd argument `xy' of raymond.rhsini to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        xy = (double *)(PyArray_DATA(capi_xy_tmp));

    /* Processing variable zeps */
        f2py_success = double_from_pyobj(&zeps,zeps_capi,"raymond.rhsini() 4th argument (zeps) can't be converted to double");
    if (f2py_success) {
    /* Processing variable nhor */
    if (nhor_capi == Py_None) nhor = shape(rhs, 0); else
        f2py_success = int_from_pyobj(&nhor,nhor_capi,"raymond.rhsini() 1st keyword (nhor) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(rhs, 0) == nhor,"shape(rhs, 0) == nhor","1st keyword nhor","rhsini:nhor=%d",nhor) {
    /* Processing variable n */
    if (n_capi == Py_None) n = shape(rhs, 1); else
        f2py_success = int_from_pyobj(&n,n_capi,"raymond.rhsini() 2nd keyword (n) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(rhs, 1) == n,"shape(rhs, 1) == n","2nd keyword n","rhsini:n=%d",n) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&nhor,&n,&istep,xy,rhs,&zeps);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_rhs_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(rhs, 1) == n)*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    } /*CHECKSCALAR(shape(rhs, 0) == nhor)*/
    } /*if (f2py_success) of nhor*/
    /* End of cleaning variable nhor */
    } /*if (f2py_success) of zeps*/
    /* End of cleaning variable zeps */
    if((PyObject *)capi_xy_tmp!=xy_capi) {
        Py_XDECREF(capi_xy_tmp); }
    }  /*if (capi_xy_tmp == NULL) ... else of xy*/
    /* End of cleaning variable xy */
    }  /*if (capi_rhs_tmp == NULL) ... else of rhs*/
    /* End of cleaning variable rhs */
    } /*if (f2py_success) of istep*/
    /* End of cleaning variable istep */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of rhsini *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"raymond",-1,{{-1}},0,(char *)F_FUNC(raymond,RAYMOND),(f2py_init_func)f2py_rout_raymond_raymond,doc_f2py_rout_raymond_raymond},
    {"impfila",-1,{{-1}},0,(char *)F_FUNC(impfila,IMPFILA),(f2py_init_func)f2py_rout_raymond_impfila,doc_f2py_rout_raymond_impfila},
    {"filsub",-1,{{-1}},0,(char *)F_FUNC(filsub,FILSUB),(f2py_init_func)f2py_rout_raymond_filsub,doc_f2py_rout_raymond_filsub},
    {"invlow_v",-1,{{-1}},0,(char *)F_FUNC_US(invlow_v,INVLOW_V),(f2py_init_func)f2py_rout_raymond_invlow_v,doc_f2py_rout_raymond_invlow_v},
    {"rhsini",-1,{{-1}},0,(char *)F_FUNC(rhsini,RHSINI),(f2py_init_func)f2py_rout_raymond_rhsini,doc_f2py_rout_raymond_rhsini},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "raymond",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_raymond(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = raymond_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module raymond (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.23.5");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'raymond' is auto-generated with f2py (version:1.23.5).\nFunctions:\n"
"    f = raymond(f,nlon,nlat,eps,nlev=shape(f, 1),overwrite_f=0)\n"
"    f = impfila(f,nlon,nlat,eps,nx,nstep,nlev=shape(f, 1),overwrite_f=0)\n"
"    xy = filsub(nstep,xy,eps,wrk,nlon=shape(xy, 0),nlat=shape(xy, 1),nx=shape(wrk, 0),overwrite_xy=0)\n"
"    invlow_v(bb,xans,h,ep,init,a,b,c,d,e,delta,beta,w,gam,ap,f,z,pi,np=shape(bb, 0),n=shape(bb, 1))\n"
"    rhs = rhsini(istep,xy,rhs,zeps,nhor=shape(rhs, 0),n=shape(rhs, 1),overwrite_rhs=0)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.23.5");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    raymond_error = PyErr_NewException ("raymond.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_raymond_error", raymond_error);
    Py_DECREF(raymond_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }





/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"raymond");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
